// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Evento struct {
	ID        int32
	Nombre    string
	Capacidad int32
	Fecha     time.Time
}

type Ticket struct {
	ID        int32
	IDUsuario int32
	IDEvento  int32
	Fecha     time.Time
}

type Usuario struct {
	ID     int32
	Nombre string
	Email  string
}
