// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const crearEvento = `-- name: CrearEvento :one
INSERT INTO eventos (nombre, capacidad, fecha)
VALUES ($1, $2, $3)
RETURNING id, nombre, capacidad, fecha
`

type CrearEventoParams struct {
	Nombre    string
	Capacidad int32
	Fecha     time.Time
}

func (q *Queries) CrearEvento(ctx context.Context, arg CrearEventoParams) (Evento, error) {
	row := q.db.QueryRowContext(ctx, crearEvento, arg.Nombre, arg.Capacidad, arg.Fecha)
	var i Evento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Capacidad,
		&i.Fecha,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one
INSERT INTO usuarios (nombre, email)
VALUES ($1, $2)
RETURNING id, nombre, email
`

type CrearUsuarioParams struct {
	Nombre string
	Email  string
}

func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.Nombre, arg.Email)
	var i Usuario
	err := row.Scan(&i.ID, &i.Nombre, &i.Email)
	return i, err
}

const eliminarTicket = `-- name: EliminarTicket :exec
DELETE FROM tickets
WHERE id = $1
`

func (q *Queries) EliminarTicket(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarTicket, id)
	return err
}

const listarEventos = `-- name: ListarEventos :many
SELECT id, nombre, capacidad, fecha FROM eventos
ORDER BY fecha ASC
`

func (q *Queries) ListarEventos(ctx context.Context) ([]Evento, error) {
	rows, err := q.db.QueryContext(ctx, listarEventos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evento
	for rows.Next() {
		var i Evento
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Capacidad,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTicketsPorUsuario = `-- name: ListarTicketsPorUsuario :many
SELECT 
    t.id AS ticket_id,
    e.id AS evento_id,
    e.nombre AS evento_nombre,
    e.fecha AS evento_fecha
FROM tickets t
JOIN eventos e ON t.id_evento = e.id
WHERE t.id_usuario = $1
`

type ListarTicketsPorUsuarioRow struct {
	TicketID     int32
	EventoID     int32
	EventoNombre string
	EventoFecha  time.Time
}

func (q *Queries) ListarTicketsPorUsuario(ctx context.Context, idUsuario int32) ([]ListarTicketsPorUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, listarTicketsPorUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTicketsPorUsuarioRow
	for rows.Next() {
		var i ListarTicketsPorUsuarioRow
		if err := rows.Scan(
			&i.TicketID,
			&i.EventoID,
			&i.EventoNombre,
			&i.EventoFecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerCapacidadReservada = `-- name: ObtenerCapacidadReservada :one
SELECT COUNT(*) FROM tickets
WHERE id_evento = $1
`

func (q *Queries) ObtenerCapacidadReservada(ctx context.Context, idEvento int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, obtenerCapacidadReservada, idEvento)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const obtenerEventoPorID = `-- name: ObtenerEventoPorID :one
SELECT id, nombre, capacidad, fecha FROM eventos
WHERE id = $1 LIMIT 1
`

func (q *Queries) ObtenerEventoPorID(ctx context.Context, id int32) (Evento, error) {
	row := q.db.QueryRowContext(ctx, obtenerEventoPorID, id)
	var i Evento
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Capacidad,
		&i.Fecha,
	)
	return i, err
}

const reservarTicket = `-- name: ReservarTicket :one
INSERT INTO tickets (id_usuario, id_evento)
VALUES ($1, $2)
RETURNING id, id_usuario, id_evento, fecha
`

type ReservarTicketParams struct {
	IDUsuario int32
	IDEvento  int32
}

func (q *Queries) ReservarTicket(ctx context.Context, arg ReservarTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, reservarTicket, arg.IDUsuario, arg.IDEvento)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.IDUsuario,
		&i.IDEvento,
		&i.Fecha,
	)
	return i, err
}
